# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-02 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181002_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='click_name',
            new_name='click_num',
        ),
    ]
