# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-02 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20181002_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(default='', max_length=100, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='详细地址'),
        ),
    ]
